.github/workflows/ci.yaml
.travis.yml
composer.json
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSizeExtensionTest.php
eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/FileSizeExtension.php
phpunit-integration-legacy.xml

Technical PR to test merge-up of https://github.com/ezsystems/ezplatform-kernel/pull/219.

Merged up ezsystems/ezplatform-kernel#219

---

src/contracts/Repository/Values/Content/Query/Criterion/Ancestor.php
src/lib/Limitation/SubtreeLimitationType.php

| **JIRA issue**                          | [IBX-1517](https://issues.ibexa.co/browse/IBX-1517), [IBX-1518](https://issues.ibexa.co/browse/IBX-1518)
| **Target Ibexa version** | `v3.3` (original)
Merge up for:
* https://github.com/ezsystems/ezplatform-kernel/pull/262
* https://github.com/ezsystems/ezplatform-kernel/pull/261/

Ibx 1517+1518 merge up

---

src/lib/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php

| **JIRA issue**                          | [IBX-1521](https://issues.ibexa.co/browse/IBX-1521)

Merge IBX-1521

---

src/lib/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php

| **Type**                                   | feature/bug/improvement

Merge ezsystems/ezplatform-kernel#267

---

src/bundle/RepositoryInstaller/IbexaRepositoryInstallerBundle.php

IBX-1334: Rebranded ibexa/core to use new namespaces

---

src/bundle/Debug/Resources/views/Profiler/layout.html.twig

| **JIRA issue**                          | -
| **Type**                                   | -

Changed profiler logo to Ibexa

---

src/lib/MVC/Symfony/Routing/UrlAliasRouter.php
src/lib/MVC/Symfony/Routing/UrlWildcardRouter.php
tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ez_path.test
tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ez_url.test
tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ibexa_path.test
tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ibexa_url.test

IBX-1998: Rebranded routes in ibexa/core repository

---

tests/integration/Core/Repository/Values/Content/DefaultLanguageCodeForContentTest.php

[Rebranding] Cleanup

---

src/lib/Resources/settings/search_engines/legacy/criterion_handlers_content.yml
src/lib/Resources/settings/search_engines/legacy/criterion_handlers_location.yml
src/lib/Resources/settings/search_engines/legacy/sort_clause_handlers_content.yml
src/lib/Resources/settings/search_engines/legacy/sort_clause_handlers_location.yml

JIRA: https://issues.ibexa.co/browse/IBX-1694

IBX-1694: Rebrand service tag leftovers

---

src/bundle/Core/Resources/config/papi.yml
src/bundle/Core/Resources/config/templating.yml
src/lib/Resources/settings/indexable_fieldtypes.yml
src/lib/Resources/settings/repository/inner.yml

IBX-1696: Removed class parameters from ibexa/core repository

---

src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
tests/lib/Repository/LegacySchemaImporter.php

IBX-1853: Used rebranded namespaces in comments

---

src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
src/bundle/Core/Translation/GlobCollector.php

| **JIRA issue**                          | [IBX-1821](https://issues.ibexa.co/browse/IBX-1821)
Since version 4.x way of storing, generating, and using translation differs. This PR introduces changes that are needed. Now translations are stored in one repository (ibexa/i18n) in `translations` directory. To test it, for now, you need to manually install this package and clear the cache.
https://github.com/ibexa/engineering/wiki/Translations

IBX-1821: Changed path where translations are looked for

---

src/bundle/Core/EventListener/ConfigScopeListener.php
src/bundle/Core/Resources/config/fieldtype_services.yml
src/bundle/IO/Resources/config/io.yml
src/contracts/MVC/EventSubscriber/ConfigScopeChangeSubscriber.php
src/lib/IO/Adapter/LocalAdapter.php
src/lib/IO/ConfigScopeChangeAwareIOService.php
tests/lib/IO/ConfigScopeChangeAwareIOServiceTest.php

Merge up of https://github.com/ezsystems/ezplatform-kernel/pull/287

Merge up of ezsystems/ezplatform-kernel#287

---

src/bundle/Core/Features/Context/ContentTypeContext.php

JIRA: https://issues.ibexa.co/browse/IBX-2322

[Behat] Removed unused variable

---

src/lib/FieldType/Image/ImageThumbnailStrategy.php

| **JIRA issue**                          | [IBX-2264](https://issues.ibexa.co/browse/IBX-2264)
Parent PR: https://github.com/ezsystems/ezplatform-kernel/pull/288

Merge IBX-2264: Handled missing thumbnail images

---

src/contracts/Ibexa.php

When merging upstream it needs to be changed to 4.1.0

Bumped version after 4.0.3 release

---

src/contracts/Search/Field.php

| **Target Ibexa version** | `v4.1`
Adds methods that were missed during merge up.

Added missing getter methods to Search Field class

---

src/lib/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
tests/integration/Core/Repository/LocationServiceTest.php
tests/lib/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabaseTest.php

Merge up of ezsystems/ezplatform-kernel#310

Merged branch '1.3' of ezsystems/ezplatform-kernel into 4.1

---

src/lib/FieldType/Relation/Type.php
src/lib/FieldType/RelationList/Type.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/RelationListConverter.php
tests/integration/Core/Repository/FieldType/RelationIntegrationTest.php
tests/integration/Core/Repository/FieldType/RelationListIntegrationTest.php
tests/lib/FieldType/RelationListTest.php
tests/lib/FieldType/RelationTest.php
tests/lib/Persistence/Legacy/Content/FieldValue/Converter/RelationListTest.php
tests/lib/Persistence/Legacy/Content/FieldValue/Converter/RelationTest.php

| **JIRA issue**                          | https://issues.ibexa.co/browse/IBX-2937
- https://github.com/ibexa/admin-ui/pull/432
- https://github.com/ibexa/content-forms/pull/31

IBX-2937: Added new relation starting location options

---

src/contracts/Test/IbexaTestKernel.php

| **Type**                                   | feature/bug/improvement

Temp 1.3 to 4.2

---

.github/workflows/ci.yaml

The same code as in https://github.com/ibexa/fieldtype-richtext/pull/54 , this time in `core` 😉

[CI] Removed hardcoded Solr version and switched to one relying on branch-alias

---

src/bundle/Core/Resources/translations/forms.en.xliff

| **JIRA issue**                          | [IBX-4452](https://issues.ibexa.co/browse/IBX-4452)

IBX-4452: Added missing line of translation

---

src/bundle/Core/DependencyInjection/Compiler/SiteAccessMatcherRegistryPass.php

| **JIRA issue**                          | [IBX-4722](https://issues.ibexa.co/browse/IBX-4722)
| **Target Ibexa version** | `v4.3`

IBX-4722: Rebranded ezplatform.siteaccess.matcher tag

---

src/bundle/Core/Imagine/VariationPathGenerator/WebpFormatVariationPathGenerator.php
src/bundle/Core/Resources/config/image.yml
tests/bundle/Core/Imagine/VariationPathGenerator/WebpFormatVariationPathGeneratorTest.php

This is a technical PR to run CI for merged up changes to 4.4.x-dev due to found conflict during merge.

IBX-4647: Merged up to 4.4

---

phpstan-baseline.neon
src/bundle/Debug/Collector/PersistenceCacheCollector.php

| **JIRA issue**                          | N/a
| **Type**                                   | -

Fixed errors reported by phpstan

---

phpstan-baseline.neon

Updated phpstan baseline

---

phpstan-baseline-7.4.neon
phpstan-baseline.neon

Testing merge up of #324 due to inconsistent local results.

[Fast forward] Merged branch '4.5'

---

phpstan-baseline.neon
src/lib/Limitation/RoleLimitationType.php

| **JIRA issue**                          | [IBX-7838](https://issues.ibexa.co/browse/IBX-7838)

IBX-7838: Corrected message an error for InvalidArgumentType

---

phpstan-baseline.neon
tests/bundle/Core/EventSubscriber/TrustedHeaderClientIpEventSubscriberTest.php

Regenerated PHPStan baseline

---

src/bundle/Core/DependencyInjection/Compiler/SecurityPass.php

| :ticket: Issue | IBX-8323 |
- https://github.com/ibexa/core/pull/396

Deprecated `CONSTANT_AUTH_TIME_SETTING`

---

phpstan-baseline.neon

PHPStan Baseline update, just checking if other jobs are passing.

[PHPStan] Aligned baseline after PHPStan release

---

phpstan-baseline-7.4.neon
phpstan-baseline-gte-8.0.neon
phpstan-baseline.neon
src/bundle/Core/EventListener/SessionInitByPostListener.php
tests/bundle/Core/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessorTest.php

https://github.com/ibexa/core/actions/runs/11177425913/job/31072880197

[PHPStan] Fixed errors after PHPStan update

---

phpstan-baseline.neon

Seems like external changes removed two of the PHPStan errors.

Regenerated PHPStan

---

phpstan-baseline-7.4.neon
phpstan-baseline.neon

- https://github.com/ibexa/core/pull/461
Unblocking opened PRs. Seems it's just change of wording of messages and some messages disappearing.

[PHPStan] Updated baseline after PHPStan release

---

phpstan-baseline-7.4.neon
phpstan-baseline.neon

Ref: https://github.com/ibexa/core/actions/runs/13050902261/job/36410764033?pr=471#step:6:19

[PHPStan] Regenerated baseline

---

src/bundle/Core/Resources/views/content_fields.html.twig

| :ticket: Issue | [IBX-9326](https://issues.ibexa.co/browse/IBX-9326) |

IBX-9326: Fixed missing class attribute for image field Twig block

---

src/lib/Search/Common/FieldValueMapper/DateMapper.php

Refactored DateMapper to move the date conversion logic into a separate private method, improving readability and maintainability.

Refactored DateMapper for better date conversion handling and code readability

---

phpstan-baseline.neon
src/contracts/Repository/Values/Content/Trash/SearchResult.php
tests/integration/Core/Repository/TrashServiceTest.php

- https://github.com/ibexa/rector/pull/23
- https://github.com/ibexa/admin-ui/pull/1467
Refactored SearchResult::$count to SearchResult::$totalCount deprecation

Refactored SearchResult::$count to SearchResult::$totalCount deprecation

---

phpstan-baseline.neon
src/lib/Persistence/Legacy/Content/Language/MaskGenerator.php
tests/lib/Persistence/Legacy/Content/Language/MaskGeneratorTest.php

Removed deprecated method MaskGenerator::generateLanguageMask

Removed deprecated method MaskGenerator::generateLanguageMask

---

phpstan-baseline.neon
src/lib/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/BinaryFileConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/CheckboxConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/CountryConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/DateConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/EmailAddressConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/FloatConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/ISBNConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/IntegerConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/KeywordConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/MapLocationConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/MediaConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/NullConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/SelectionConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/TextBlockConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/TextLineConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/TimeConverter.php
src/lib/Persistence/Legacy/Content/FieldValue/Converter/UrlConverter.php

Removed deprecated create method

Removed deprecated create method

---

phpstan-baseline-7.4.neon
phpstan-baseline.neon

Seems reported baseline message changed after PHPStan release.

[PHPStan] Regenerated baseline after PHPStan release

---

phpstan-baseline.neon
src/lib/Repository/Values/Content/Query/Criterion/PermissionSubtree.php

Removed deprecated method PermissionSubtree::createFromQueryBuilder

Removed deprecated method PermissionSubtree::createFromQueryBuilder

---

phpstan-baseline.neon
src/lib/Search/Common/FieldNameResolver.php
tests/integration/Core/Repository/FieldType/SearchBaseIntegrationTest.php
tests/lib/Search/FieldNameResolverTest.php

Changed deprecated method FieldNameResolver::getFieldNames to FieldNameResolver::getFieldTypes

Changed deprecated method FieldNameResolver::getFieldNames to FieldNameResolver::getFieldTypes

---

phpstan-baseline.neon
tests/integration/Core/Repository/BaseTest.php
tests/integration/Core/Repository/SearchServiceTest.php

Removed deprecation BaseTest::isVersion4 and SearchServiceTest::testDeprecatedCriteriaProperty

Removed deprecation BaseTest::isVersion4 and SearchServiceTest::testDeprecatedCriteriaProperty

---

phpstan-baseline.neon

[PHPStan] Regenerated PHPStan baseline

---

phpstan-baseline-gte-8.3.neon
phpstan-baseline.neon

[PHPStan] Regenerated PHPStan baseline for PHP < 8.3

---

phpstan-baseline.neon
src/bundle/Debug/DependencyInjection/Compiler/DataCollectorPass.php
src/bundle/Debug/Resources/config/services.yml
tests/bundle/Debug/DependencyInjection/Compiler/DataCollectorPassTest.php
tests/lib/Limitation/MemberOfLimitationTypeTest.php

| :ticket: Issue | IBX-9697 |
- https://github.com/ibexa/twig-components/pull/2
Added priority field to ibexa data collector

IBX-9697: Added priority attribute to ibexa data collector

---

phpstan-baseline.neon

Added to baseline here.
https://github.com/ibexa/core/pull/525/files
but there were fixed in
https://github.com/ibexa/core/pull/526

[CI] Removed fixed issues from baseline

---

.github/workflows/gha-docker-solr.yaml
.github/workflows/reviewers.yaml

ENG-140: Added auto-assign reviewers GH workflow

---

src/bundle/Core/Imagine/Filter/Loader/BorderFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/CropFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/GrayscaleFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ReduceNoiseFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleDownOnlyFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleExactFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleHeightFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScalePercentFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/ScaleWidthFilterLoader.php
src/bundle/Core/Imagine/Filter/Loader/SwirlFilterLoader.php
src/bundle/Core/Imagine/VariationPurger/LegacyStorageImageFileList.php
src/bundle/IO/Migration/FileLister/FileIterator/LegacyStorageFileIterator.php

Added return type declarations

Added return type declarations

---

src/contracts/Repository/Iterator/BatchIterator.php

Add return type declaration for current() method in BatchIterator

Add return type declaration for current() method in BatchIterator

---

src/contracts/Persistence/Content/Type.php
src/contracts/Persistence/Content/Type/CreateStruct.php
src/contracts/Persistence/Content/Type/UpdateStruct.php
src/lib/Repository/Mapper/ContentTypeDomainMapper.php

Follow up for https://github.com/ibexa/core/pull/575
N/A
N/A

Fixed "Cannot assign null to property ContentType::$urlAliasSchema of type string"

---

src/bundle/Core/Resources/config/storage/legacy/schema.yaml
src/lib/Persistence/Legacy/UserPreference/Gateway/DoctrineDatabase.php
tests/integration/Core/Repository/_fixtures/Legacy/data/test_data.yaml

IBX-9941: Renamed ibexa_preferences into ibexa_user_preference

---

data/mysql/cleandata.sql
data/postgresql/cleandata.sql

IBX-9941: Fixed ibexa_preferences wrong name in clean data

---

src/lib/Repository/Validator/Constraint/LocationIsContainerContentTypeValidator.php

| :ticket: Issue | IBX-7801 |
Follow up for https://github.com/ibexa/core/pull/598. Container validation should be skipped for root location. 
See https://github.com/ibexa/admin-ui/actions/runs/16126312132/job/45503938675?pr=1601#step:10:2006
N/A
N/A

Skipped container validation for root location

---

src/bundle/Core/Cache/Warmer/ProxyCacheWarmer.php

Fixed strict type hints of ProxyCacheWarmer.

IBX-9727: Fixed strict types of ProxyCacheWarmer

---

src/bundle/Core/Resources/translations/forms.en.xlf
src/bundle/Core/Resources/translations/ibexa_fieldtypes.en.xlf
src/bundle/Core/Resources/translations/ibexa_repository_exceptions.en.xlf

| :ticket: Issue |  |
- #590
Extracted & added missing translations using full-stack app JMS extractor. Using `TranslationTest` here is complicated because it resides in `ibexa/test-core` (which requires `ibexa/core` - creating a cyclic dependency). Moreover some changes to test kernel would be required.
For now adding just translations. The most of it is a result of #590 changes.

[UI][i18n] Added missing translations

---

src/contracts/Validation/Constraint/UniqueIdentifier.php
src/contracts/Validation/Constraint/UniqueIdentifierValidator.php
tests/lib/Validation/Constraint/UniqueIdentifierValidatorTest.php

Identifier uniqueness check occurs often and is done in a similar way every time. This PR aims to remove this duplication across packages.

Added `UniqueIdentifier` abstract constraint to reduce code duplication

---

src/contracts/Repository/ContentService.php

Not super obvious, as there should always be content related to versionInfo but it can happen with collaboration sessions & notifications.
Should easily clear some baselines and add 🟩 to my profile.

[PHPStan] Added missing throw doc

---

src/bundle/IO/Resources/config/io.yml

| :ticket: Issue | IBX-10657 |
These changes have already been implemented in v5.0, so this PR is a backport from: https://github.com/ibexa/core/pull/613

IBX-10657: Fixed invalid IO services definitions

---

.github/workflows/ci.yaml
phpstan-baseline.neon

[CI] Bumped actions' versions + regenerated PHPStan baseline
